---
# handlers file for clearml

- name: reload service
  systemd:
    daemon_reload: yes

- name: start service
  systemd:
    name: "{{ clearml_service }}.service"
    state: started
    enabled: yes

- name: stop service
  systemd:
    name: "{{ clearml_service }}.service"
    state: stopped

- name: restart service
  systemd:
    name: "{{ clearml_service }}.service"
    state: restarted
