---
## Install python
- name: Update all packages to their latest version on Redhat and family
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_facts['os_family']|lower == 'debian'

- name: install python on Ubuntu and family
  apt:
    pkg: 
      - python3
      - python3-pip
    state: latest
  when: ansible_facts['os_family']|lower == 'debian'

## Install python
- name: Upgrade all packages to the latest version on Redhat and family
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'

- name: install python on Redhat and family
  yum:
    name: python38
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'


## Install clearml-agent package with pip
- name: install clearml-agent
  pip:
    name: "{{ app_name }}"

## Create config file
- name: configure clearml-agent
  template:
    src: clearml.conf.j2
    dest: ~/clearml.conf
    owner: "{{ clearml_user }}"
    group: "{{ clearml_user }}"
    mode: 0644
  register: clearmlconfig

## Create service file adn start clearml-agent
- name: Create service file for clearml-agent
  template:
    src: "{{ clearml_service }}.service.j2"
    dest: "/lib/systemd/system/{{ clearml_service }}.service"
    owner: "{{ clearml_user }}"
    group: "{{ clearml_user }}"
    mode: 0644
  register: clearmlservice

- name: Make sure service is started and enabled
  systemd:
    name: clearml-agent
    state: started
    enabled: yes


## Restart clearml-agent service when config or service update
- name: Restart clearml-service agent
  debug:
    msg: Performing restart!!!
  notify:
    - reload service
    - restart service

