---
## Create iuser in config file
- name: configure authentication and create users
  template:
    src: apiserver.conf.j2
    dest: /opt/clearml/config/apiserver.conf
    owner: 1000
    group: 1000
    mode: 0644
  register: clearmlconfig

## Restart clearml-agent service when config or service update
- name: Restart clearml-service server
  debug:
    msg: Performing restart!!!
  notify:
    - reload service
    - restart service
  when: clearmlconfig.changed

