---

- name: Setup repositorie and install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Get Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Setup repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Increase vm.max_map_count for Elasticsearch in Docker
  sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_file: /etc/sysctl.d/99-clearml.conf
    reload: no
  register: sysctlconfig

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  when: sysctlconfig.changed

- name: Download docker-compose
  get_url:
    url:  https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['machine'] }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create a symbolic link for docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
