---
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: Install python on Ubuntu and family
  apt:
    pkg:
      - python3
      - python3-pip
    state: latest

- name: Install docker-compose module
  pip:
    name: docker-compose

- name: Create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
  loop:
    - /opt/clearml/data/mongo/db
    - /opt/clearml/data/mongo/configdb
    - /opt/clearml/data/redis
    - /opt/clearml/logs
    - /opt/clearml/config
    - /opt/clearml/data/fileserver

- name: Change app directory ownership recursive
  file:
    dest: /opt/clearml
    owner: 1000
    group: 1000
    mode: 0775
    recurse: yes

# src directory path starts at the parent playbook directory!!
- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/clearml/docker-compose.yml
    owner: "{{ clearml_user }}"
    owner: "{{ clearml_user }}"
    mode: 0644
  register: dockercompose

## Create service file for clearml server
- name: Create service file for clearml-server
  template:
    src: "{{ clearml_service }}.service.j2"
    dest: "/lib/systemd/system/{{ clearml_service }}.service"
    owner: "{{ clearml_user }}"
    group: "{{ clearml_user }}"
    mode: 0644
  register: clearmlservice

- name: Make sure server starts and enabled
  debug:
    msg: "Server is starting ans will be available at https://{{ server_public_dns }}"
  notify:
    - start service

## Restart clearml-agent service when config or service update
- name: Restart clearml-service server
  debug:
    msg: Performing restart!!!
  notify:
    - reload service
    - restart service
  when: clearmlservice.changed or dockercompose.changed

