---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install python on Ubuntu and family
  apt:
    pkg:
      - python3
      - python3-pip
    state: latest

- name: Install docker-compose module
  pip:
    name: docker-compose

- name: Create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
  loop:
    - /opt/clearml/data/mongo/db
    - /opt/clearml/data/mongo/configdb
    - /opt/clearml/data/redis
    - /opt/clearml/logs
    - /opt/clearml/config
    - /opt/clearml/data/fileserver

# src directory path starts at the parent playbook directory!!
- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
    src: docker-compose/docker-compose.yml
    dest: /opt/clearml/docker-compose.yml



- name: Increase vm.max_map_count for Elasticsearch in Docker
  command: |
    echo "vm.max_map_count=262144" > /tmp/99-clearml.conf
    mv /tmp/99-clearml.conf /etc/sysctl.d/99-clearml.conf
    sysctl -w vm.max_map_count=262144
    service docker restart


## Create service file for clearml server
- name: Create service file for clearml-agent
  template:
    src: "{{ clearml_service }}.service.j2"
    dest: "/lib/systemd/system/{{ clearml_service }}.service"
    owner: "{{ clearml_user }}"
    group: "{{ clearml_user }}"
    mode: 0644
  register: clearmlservice


## Restart clearml-agent service when config or service update
- name: Restart clearml-service agent
  debug:
    msg: Performing restart!!!
  notify:
    - reload service
    - restart clearml
  when: clearmlconfig.changed or clearmlservice.changed

